window.LUK_CATALOG = [
  {
    "id": "ACETATOBQ23101",
    "category": "Acetato",
    "group": "Acetato",
    "line": "BQ",
    "code": "23101",
    "price": 319.9,
    "priceLabel": "R$ 319,90",
    "note": "",
    "size": "53-17-145",
    "colors": 6,
    "image": "assets/modelos/23101.jpg"
  },
  {
    "id": "ACETATOBQ23102",
    "category": "Acetato",
    "group": "Acetato",
    "line": "BQ",
    "code": "23102",
    "price": 329.9,
    "priceLabel": "R$ 329,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/23102.jpg"
  },
  {
    "id": "ACETATOBQ23103",
    "category": "Acetato",
    "group": "Acetato",
    "line": "BQ",
    "code": "23103",
    "price": 349.9,
    "priceLabel": "R$ 349,90",
    "note": "",
    "size": "",
    "colors": 6,
    "image": "assets/modelos/23103.jpg"
  },
  {
    "id": "ACETATOBQ23104",
    "category": "Acetato",
    "group": "Acetato",
    "line": "BQ",
    "code": "23104",
    "price": 319.9,
    "priceLabel": "R$ 319,90",
    "note": "",
    "size": "",
    "colors": 6,
    "image": "assets/modelos/23104.jpg"
  },
  {
    "id": "ACETATOBQ23105",
    "category": "Acetato",
    "group": "Acetato",
    "line": "BQ",
    "code": "23105",
    "price": 449.9,
    "priceLabel": "R$ 449,90",
    "note": "",
    "size": "",
    "colors": 5,
    "image": "assets/modelos/23105.jpg"
  },
  {
    "id": "ACETATOBQ23106",
    "category": "Acetato",
    "group": "Acetato",
    "line": "BQ",
    "code": "23106",
    "price": 419.9,
    "priceLabel": "R$ 419,90",
    "note": "",
    "size": "",
    "colors": 6,
    "image": "assets/modelos/23106.jpg"
  },
  {
    "id": "ACETATOBQ23107",
    "category": "Acetato",
    "group": "Acetato",
    "line": "BQ",
    "code": "23107",
    "price": 349.9,
    "priceLabel": "R$ 349,90",
    "note": "",
    "size": "",
    "colors": 5,
    "image": "assets/modelos/23107.jpg"
  },
  {
    "id": "ACETATOBQ23108",
    "category": "Acetato",
    "group": "Acetato",
    "line": "BQ",
    "code": "23108",
    "price": 519.9,
    "priceLabel": "R$ 519,90",
    "note": "",
    "size": "",
    "colors": 6,
    "image": "assets/modelos/23108.jpg"
  },
  {
    "id": "ACETATOBQ23109",
    "category": "Acetato",
    "group": "Acetato",
    "line": "BQ",
    "code": "23109",
    "price": 449.9,
    "priceLabel": "R$ 449,90",
    "note": "",
    "size": "",
    "colors": 6,
    "image": "assets/modelos/23109.jpg"
  },
  {
    "id": "ACETATOBQ23110",
    "category": "Acetato",
    "group": "Acetato",
    "line": "BQ",
    "code": "23110",
    "price": 389.9,
    "priceLabel": "R$ 389,90",
    "note": "",
    "size": "",
    "colors": 5,
    "image": "assets/modelos/23110.jpg"
  },
  {
    "id": "ACETATOBQ23111",
    "category": "Acetato",
    "group": "Acetato",
    "line": "BQ",
    "code": "23111",
    "price": 519.9,
    "priceLabel": "R$ 519,90",
    "note": "",
    "size": "51-18-148",
    "colors": 4,
    "image": "assets/modelos/23111.jpg"
  },
  {
    "id": "ACETATOBQ23112",
    "category": "Acetato",
    "group": "Acetato",
    "line": "BQ",
    "code": "23112",
    "price": 489.9,
    "priceLabel": "R$ 489,90",
    "note": "",
    "size": "",
    "colors": 5,
    "image": "assets/modelos/23112.jpg"
  },
  {
    "id": "ACETATOBQ23113",
    "category": "Acetato",
    "group": "Acetato",
    "line": "BQ",
    "code": "23113",
    "price": 449.9,
    "priceLabel": "R$ 449,90",
    "note": "",
    "size": "",
    "colors": 6,
    "image": "assets/modelos/23113.jpg"
  },
  {
    "id": "ACETATOBQ23114",
    "category": "Acetato",
    "group": "Acetato",
    "line": "BQ",
    "code": "23114",
    "price": 519.9,
    "priceLabel": "R$ 519,90",
    "note": "",
    "size": "",
    "colors": 5,
    "image": "assets/modelos/23114.jpg"
  },
  {
    "id": "ACETATOBQ23115",
    "category": "Acetato",
    "group": "Acetato",
    "line": "BQ",
    "code": "23115",
    "price": 549.9,
    "priceLabel": "R$ 549,90",
    "note": "",
    "size": "",
    "colors": 6,
    "image": "assets/modelos/23115.jpg"
  },
  {
    "id": "ACETATOBQ23116",
    "category": "Acetato",
    "group": "Acetato",
    "line": "BQ",
    "code": "23116",
    "price": 489.9,
    "priceLabel": "R$ 489,90",
    "note": "",
    "size": "",
    "colors": 6,
    "image": "assets/modelos/23116.jpg"
  },
  {
    "id": "ACETATOBQ23117",
    "category": "Acetato",
    "group": "Acetato",
    "line": "BQ",
    "code": "23117",
    "price": 489.9,
    "priceLabel": "R$ 489,90",
    "note": "",
    "size": "48-23-145",
    "colors": 5,
    "image": "assets/modelos/23117.jpg"
  },
  {
    "id": "ACETATOBQ23118",
    "category": "Acetato",
    "group": "Acetato",
    "line": "BQ",
    "code": "23118",
    "price": 389.9,
    "priceLabel": "R$ 389,90",
    "note": "",
    "size": "",
    "colors": 5,
    "image": "assets/modelos/23118.jpg"
  },
  {
    "id": "ACETATOBQ23119",
    "category": "Acetato",
    "group": "Acetato",
    "line": "BQ",
    "code": "23119",
    "price": 389.9,
    "priceLabel": "R$ 389,90",
    "note": "",
    "size": "",
    "colors": 5,
    "image": "assets/modelos/23119.jpg"
  },
  {
    "id": "ACETATOBQ23120",
    "category": "Acetato",
    "group": "Acetato",
    "line": "BQ",
    "code": "23120",
    "price": 319.9,
    "priceLabel": "R$ 319,90",
    "note": "",
    "size": "",
    "colors": 5,
    "image": "assets/modelos/23120.jpg"
  },
  {
    "id": "ACETATOBQ23121",
    "category": "Acetato",
    "group": "Acetato",
    "line": "BQ",
    "code": "23121",
    "price": 349.9,
    "priceLabel": "R$ 349,90",
    "note": "",
    "size": "56-16-145",
    "colors": 4,
    "image": "assets/modelos/23121.jpg"
  },
  {
    "id": "ACETATOCLG1101",
    "category": "Acetato",
    "group": "Acetato",
    "line": "CLG",
    "code": "1101",
    "price": 519.9,
    "priceLabel": "R$ 519,90",
    "note": "",
    "size": "54-20-145",
    "colors": 5,
    "image": "assets/modelos/1101.jpg"
  },
  {
    "id": "ACETATOCLG1102",
    "category": "Acetato",
    "group": "Acetato",
    "line": "CLG",
    "code": "1102",
    "price": 489.9,
    "priceLabel": "R$ 489,90",
    "note": "",
    "size": "",
    "colors": 5,
    "image": "assets/modelos/1102.jpg"
  },
  {
    "id": "ACETATOCLG1103",
    "category": "Acetato",
    "group": "Acetato",
    "line": "CLG",
    "code": "1103",
    "price": 549.9,
    "priceLabel": "R$ 549,90",
    "note": "",
    "size": "",
    "colors": 5,
    "image": "assets/modelos/1103.jpg"
  },
  {
    "id": "ACETATOCLG1104",
    "category": "Acetato",
    "group": "Acetato",
    "line": "CLG",
    "code": "1104",
    "price": 389.9,
    "priceLabel": "R$ 389,90",
    "note": "",
    "size": "",
    "colors": 5,
    "image": "assets/modelos/1104.jpg"
  },
  {
    "id": "ACETATOCLG1105",
    "category": "Acetato",
    "group": "Acetato",
    "line": "CLG",
    "code": "1105",
    "price": 419.9,
    "priceLabel": "R$ 419,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/1105.jpg"
  },
  {
    "id": "ACETATOCLG1106",
    "category": "Acetato",
    "group": "Acetato",
    "line": "CLG",
    "code": "1106",
    "price": 449.9,
    "priceLabel": "R$ 449,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/1106.jpg"
  },
  {
    "id": "ACETATOCLG1107",
    "category": "Acetato",
    "group": "Acetato",
    "line": "CLG",
    "code": "1107",
    "price": 449.9,
    "priceLabel": "R$ 449,90",
    "note": "",
    "size": "50-19-145",
    "colors": 4,
    "image": "assets/modelos/1107.jpg"
  },
  {
    "id": "ACETATOJL1018",
    "category": "Acetato",
    "group": "Acetato",
    "line": "JL",
    "code": "1018",
    "price": 389.9,
    "priceLabel": "R$ 389,90",
    "note": "",
    "size": "51-16-145",
    "colors": 5,
    "image": "assets/modelos/1018.jpg"
  },
  {
    "id": "ACETATOJL1021",
    "category": "Acetato",
    "group": "Acetato",
    "line": "JL",
    "code": "1021",
    "price": 399.9,
    "priceLabel": "R$ 399,90",
    "note": "",
    "size": "53-17-142",
    "colors": 6,
    "image": "assets/modelos/1021.jpg"
  },
  {
    "id": "ACETATOMAGNO2701",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Magno",
    "code": "2701",
    "price": 349.9,
    "priceLabel": "R$ 349,90",
    "note": "",
    "size": "50-21-145",
    "colors": 4,
    "image": "assets/modelos/2701.jpg"
  },
  {
    "id": "ACETATOMAGNO2702",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Magno",
    "code": "2702",
    "price": 389.9,
    "priceLabel": "R$ 389,90",
    "note": "",
    "size": "52-17-145",
    "colors": 4,
    "image": "assets/modelos/2702.jpg"
  },
  {
    "id": "ACETATOMAGNO2703",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Magno",
    "code": "2703",
    "price": 419.9,
    "priceLabel": "R$ 419,90",
    "note": "",
    "size": "51-18-145",
    "colors": 4,
    "image": "assets/modelos/2703.jpg"
  },
  {
    "id": "ACETATOMAGNO2704",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Magno",
    "code": "2704",
    "price": 429.9,
    "priceLabel": "R$ 429,90",
    "note": "",
    "size": "48-17-145",
    "colors": 3,
    "image": "assets/modelos/2704.jpg"
  },
  {
    "id": "ACETATOMAGNO2705",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Magno",
    "code": "2705",
    "price": 429.9,
    "priceLabel": "R$ 429,90",
    "note": "",
    "size": "45-25-145",
    "colors": 3,
    "image": "assets/modelos/2705.jpg"
  },
  {
    "id": "ACETATOMAGNO2706",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Magno",
    "code": "2706",
    "price": 389.9,
    "priceLabel": "R$ 389,90",
    "note": "",
    "size": "50-21-145",
    "colors": 4,
    "image": "assets/modelos/2706.jpg"
  },
  {
    "id": "ACETATOMAGNO2707",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Magno",
    "code": "2707",
    "price": 519.9,
    "priceLabel": "R$ 519,90",
    "note": "",
    "size": "48-20-145",
    "colors": 4,
    "image": "assets/modelos/2707.jpg"
  },
  {
    "id": "ACETATOMAGNO2708",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Magno",
    "code": "2708",
    "price": 389.9,
    "priceLabel": "R$ 389,90",
    "note": "",
    "size": "48-20-145",
    "colors": 4,
    "image": "assets/modelos/2708.jpg"
  },
  {
    "id": "ACETATOMAGNO2709",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Magno",
    "code": "2709",
    "price": 419.9,
    "priceLabel": "R$ 419,90",
    "note": "",
    "size": "52-17-145",
    "colors": 3,
    "image": "assets/modelos/2709.jpg"
  },
  {
    "id": "ACETATOMAGNO2710",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Magno",
    "code": "2710",
    "price": 389.9,
    "priceLabel": "R$ 389,90",
    "note": "",
    "size": "52-19-145",
    "colors": 3,
    "image": "assets/modelos/2710.jpg"
  },
  {
    "id": "ACETATOSTUDIOPREMIUMCL2601",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Studio Premium",
    "code": "CL2601",
    "price": 489.9,
    "priceLabel": "R$ 489,90",
    "note": "",
    "size": "51-19-140",
    "colors": 5,
    "image": "assets/modelos/cl2601.jpg"
  },
  {
    "id": "ACETATOSTUDIOPREMIUMCL2602",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Studio Premium",
    "code": "CL2602",
    "price": 479.9,
    "priceLabel": "R$ 479,90",
    "note": "",
    "size": "53-18-142",
    "colors": 3,
    "image": "assets/modelos/cl2602.jpg"
  },
  {
    "id": "ACETATOSTUDIOPREMIUMCL2603",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Studio Premium",
    "code": "CL2603",
    "price": 389.9,
    "priceLabel": "R$ 389,90",
    "note": "",
    "size": "52-18-145",
    "colors": 4,
    "image": "assets/modelos/cl2603.jpg"
  },
  {
    "id": "ACETATOSTUDIOPREMIUMCL2604",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Studio Premium",
    "code": "CL2604",
    "price": 429.9,
    "priceLabel": "R$ 429,90",
    "note": "",
    "size": "53-17-140",
    "colors": 4,
    "image": "assets/modelos/cl2604.jpg"
  },
  {
    "id": "ACETATOSTUDIOPREMIUMCL2605",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Studio Premium",
    "code": "CL2605",
    "price": 419.9,
    "priceLabel": "R$ 419,90",
    "note": "",
    "size": "50-19-140",
    "colors": 4,
    "image": "assets/modelos/cl2605.jpg"
  },
  {
    "id": "ACETATOSTUDIOPREMIUMCL2606",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Studio Premium",
    "code": "CL2606",
    "price": 519.9,
    "priceLabel": "R$ 519,90",
    "note": "",
    "size": "48-20-140",
    "colors": 4,
    "image": "assets/modelos/cl2606.jpg"
  },
  {
    "id": "ACETATOSTUDIOPREMIUMCL2607",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Studio Premium",
    "code": "CL2607",
    "price": 329.9,
    "priceLabel": "R$ 329,90",
    "note": "",
    "size": "51-19-140",
    "colors": 4,
    "image": "assets/modelos/cl2607.jpg"
  },
  {
    "id": "ACETATOSTUDIOPREMIUMCL2608",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Studio Premium",
    "code": "CL2608",
    "price": 419.9,
    "priceLabel": "R$ 419,90",
    "note": "",
    "size": "",
    "colors": 5,
    "image": "assets/modelos/cl2608.jpg"
  },
  {
    "id": "ACETATOSTUDIOPREMIUMCL2609",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Studio Premium",
    "code": "CL2609",
    "price": 349.9,
    "priceLabel": "R$ 349,90",
    "note": "",
    "size": "54-16-140",
    "colors": 5,
    "image": "assets/modelos/cl2609.jpg"
  },
  {
    "id": "ACETATOSTUDIOPREMIUMCL2610",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Studio Premium",
    "code": "CL2610",
    "price": 389.9,
    "priceLabel": "R$ 389,90",
    "note": "",
    "size": "54-16-140",
    "colors": 4,
    "image": "assets/modelos/cl2610.jpg"
  },
  {
    "id": "ACETATOSTUDIOPREMIUMCL2611",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Studio Premium",
    "code": "CL2611",
    "price": 319.9,
    "priceLabel": "R$ 319,90",
    "note": "",
    "size": "51-17-140",
    "colors": 4,
    "image": "assets/modelos/cl2611.jpg"
  },
  {
    "id": "ACETATOWEVASMY24001",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Wevas",
    "code": "My24001",
    "price": 389.9,
    "priceLabel": "R$ 389,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/my24001.jpg"
  },
  {
    "id": "ACETATOWEVASMY24002",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Wevas",
    "code": "My24002",
    "price": 399.9,
    "priceLabel": "R$ 399,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/my24002.jpg"
  },
  {
    "id": "ACETATOWEVASMY24003",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Wevas",
    "code": "My24003",
    "price": 379.9,
    "priceLabel": "R$ 379,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/my24003.jpg"
  },
  {
    "id": "ACETATOWEVASMY24004",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Wevas",
    "code": "My24004",
    "price": 419.9,
    "priceLabel": "R$ 419,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/my24004.jpg"
  },
  {
    "id": "ACETATOWEVASMY24005",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Wevas",
    "code": "My24005",
    "price": 389.9,
    "priceLabel": "R$ 389,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/my24005.jpg"
  },
  {
    "id": "ACETATOWEVASMY24006",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Wevas",
    "code": "My24006",
    "price": 389.9,
    "priceLabel": "R$ 389,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/my24006.jpg"
  },
  {
    "id": "ACETATOWEVASMY24007",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Wevas",
    "code": "My24007",
    "price": 419.9,
    "priceLabel": "R$ 419,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/my24007.jpg"
  },
  {
    "id": "ACETATOWEVASMY24008",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Wevas",
    "code": "My24008",
    "price": 319.9,
    "priceLabel": "R$ 319,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/my24008.jpg"
  },
  {
    "id": "ACETATOWEVASMY24009",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Wevas",
    "code": "My24009",
    "price": 349.9,
    "priceLabel": "R$ 349,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/my24009.jpg"
  },
  {
    "id": "ACETATOWEVASMY24010",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Wevas",
    "code": "My24010",
    "price": 379.9,
    "priceLabel": "R$ 379,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/my24010.jpg"
  },
  {
    "id": "ACETATOWEVASMY24011",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Wevas",
    "code": "My24011",
    "price": 419.9,
    "priceLabel": "R$ 419,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/my24011.jpg"
  },
  {
    "id": "ACETATOWEVASMY24012",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Wevas",
    "code": "My24012",
    "price": 429.9,
    "priceLabel": "R$ 429,90",
    "note": "",
    "size": "",
    "colors": 5,
    "image": "assets/modelos/my24012.jpg"
  },
  {
    "id": "ACETATOWEVASMY24013",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Wevas",
    "code": "My24013",
    "price": 389.9,
    "priceLabel": "R$ 389,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/my24013.jpg"
  },
  {
    "id": "ACETATOWEVASMY24014",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Wevas",
    "code": "My24014",
    "price": 419.9,
    "priceLabel": "R$ 419,90",
    "note": "",
    "size": "",
    "colors": 5,
    "image": "assets/modelos/my24014.jpg"
  },
  {
    "id": "ACETATOWEVASMY24015",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Wevas",
    "code": "My24015",
    "price": 319.9,
    "priceLabel": "R$ 319,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/my24015.jpg"
  },
  {
    "id": "ACETATOWEVASMY24016",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Wevas",
    "code": "My24016",
    "price": 329.9,
    "priceLabel": "R$ 329,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/my24016.jpg"
  },
  {
    "id": "ACETATOWEVASMY24017",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Wevas",
    "code": "My24017",
    "price": 519.9,
    "priceLabel": "R$ 519,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/my24017.jpg"
  },
  {
    "id": "ACETATOWEVASMY24018",
    "category": "Acetato",
    "group": "Acetato",
    "line": "Wevas",
    "code": "My24018",
    "price": 519.9,
    "priceLabel": "R$ 519,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/my24018.jpg"
  },
  {
    "id": "ACETATOYV5301",
    "category": "Acetato",
    "group": "Acetato",
    "line": "YV",
    "code": "5301",
    "price": 319.9,
    "priceLabel": "R$ 319,90",
    "note": "",
    "size": "52-19-145",
    "colors": 4,
    "image": "assets/modelos/5301.jpg"
  },
  {
    "id": "ACETATOYV5302",
    "category": "Acetato",
    "group": "Acetato",
    "line": "YV",
    "code": "5302",
    "price": 349.9,
    "priceLabel": "R$ 349,90",
    "note": "",
    "size": "49-16-135",
    "colors": 4,
    "image": "assets/modelos/5302.jpg"
  },
  {
    "id": "ACETATOYV5303",
    "category": "Acetato",
    "group": "Acetato",
    "line": "YV",
    "code": "5303",
    "price": 449.9,
    "priceLabel": "R$ 449,90",
    "note": "",
    "size": "49-20-135",
    "colors": 4,
    "image": "assets/modelos/5303.jpg"
  },
  {
    "id": "ACETATOYV5311",
    "category": "Acetato",
    "group": "Acetato",
    "line": "YV",
    "code": "5311",
    "price": 389.9,
    "priceLabel": "R$ 389,90",
    "note": "",
    "size": "50-18-135",
    "colors": 4,
    "image": "assets/modelos/5311.jpg"
  },
  {
    "id": "ACETATOYV5312",
    "category": "Acetato",
    "group": "Acetato",
    "line": "YV",
    "code": "5312",
    "price": 389.9,
    "priceLabel": "R$ 389,90",
    "note": "",
    "size": "51-17-140",
    "colors": 4,
    "image": "assets/modelos/5312.jpg"
  },
  {
    "id": "ACETATOYV5313",
    "category": "Acetato",
    "group": "Acetato",
    "line": "YV",
    "code": "5313",
    "price": 429.9,
    "priceLabel": "R$ 429,90",
    "note": "",
    "size": "52-17-140",
    "colors": 4,
    "image": "assets/modelos/5313.jpg"
  },
  {
    "id": "ACETATOYV5314",
    "category": "Acetato",
    "group": "Acetato",
    "line": "YV",
    "code": "5314",
    "price": 419.9,
    "priceLabel": "R$ 419,90",
    "note": "",
    "size": "51-18-145",
    "colors": 4,
    "image": "assets/modelos/5314.jpg"
  },
  {
    "id": "ACETATOYV5315",
    "category": "Acetato",
    "group": "Acetato",
    "line": "YV",
    "code": "5315",
    "price": 359.9,
    "priceLabel": "R$ 359,90",
    "note": "",
    "size": "53-15-140",
    "colors": 4,
    "image": "assets/modelos/5315.jpg"
  },
  {
    "id": "ACETATOYV5321",
    "category": "Acetato",
    "group": "Acetato",
    "line": "YV",
    "code": "5321",
    "price": 389.9,
    "priceLabel": "R$ 389,90",
    "note": "",
    "size": "48-19-140",
    "colors": 4,
    "image": "assets/modelos/5321.jpg"
  },
  {
    "id": "ACETATOYV5322",
    "category": "Acetato",
    "group": "Acetato",
    "line": "YV",
    "code": "5322",
    "price": 419.9,
    "priceLabel": "R$ 419,90",
    "note": "",
    "size": "50-18-140",
    "colors": 5,
    "image": "assets/modelos/5322.jpg"
  },
  {
    "id": "ACETATOYV5323",
    "category": "Acetato",
    "group": "Acetato",
    "line": "YV",
    "code": "5323",
    "price": 529.9,
    "priceLabel": "R$ 529,90",
    "note": "",
    "size": "51-17-140",
    "colors": 4,
    "image": "assets/modelos/5323.jpg"
  },
  {
    "id": "ACETATOCLIPON65XX6537",
    "category": "Acetato Clip On",
    "group": "Clip-on",
    "line": "65XX",
    "code": "6537",
    "price": 419.9,
    "priceLabel": "R$ 419,90",
    "note": "Em falta",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "ACETATOCLIPON65XX6538",
    "category": "Acetato Clip On",
    "group": "Clip-on",
    "line": "65XX",
    "code": "6538",
    "price": 449.9,
    "priceLabel": "R$ 449,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "ACETATOCLIPON65XX6540",
    "category": "Acetato Clip On",
    "group": "Clip-on",
    "line": "65XX",
    "code": "6540",
    "price": 429.9,
    "priceLabel": "R$ 429,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "ACETATOCLIPON65XX6542",
    "category": "Acetato Clip On",
    "group": "Clip-on",
    "line": "65XX",
    "code": "6542",
    "price": 429.9,
    "priceLabel": "R$ 429,90",
    "note": "Em falta",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "ACETATOCLIPON65XX6551",
    "category": "Acetato Clip On",
    "group": "Clip-on",
    "line": "65XX",
    "code": "6551",
    "price": 449.9,
    "priceLabel": "R$ 449,90",
    "note": "Em falta",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "ACETATOCLIPON65XX6553",
    "category": "Acetato Clip On",
    "group": "Clip-on",
    "line": "65XX",
    "code": "6553",
    "price": 449.9,
    "priceLabel": "R$ 449,90",
    "note": "Em falta",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "ACETATOCLIPON65XX6555",
    "category": "Acetato Clip On",
    "group": "Clip-on",
    "line": "65XX",
    "code": "6555",
    "price": 519.9,
    "priceLabel": "R$ 519,90",
    "note": "Em falta",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "ACETATOCLIPON65XX6556",
    "category": "Acetato Clip On",
    "group": "Clip-on",
    "line": "65XX",
    "code": "6556",
    "price": 519.9,
    "priceLabel": "R$ 519,90",
    "note": "Em falta",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "ACETATOCLIPONDB1001CT",
    "category": "Acetato Clip On",
    "group": "Clip-on",
    "line": "DB",
    "code": "1001-CT",
    "price": 519.9,
    "priceLabel": "R$ 519,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "ACETATOCLIPONDB1002CT",
    "category": "Acetato Clip On",
    "group": "Clip-on",
    "line": "DB",
    "code": "1002-CT",
    "price": 539.9,
    "priceLabel": "R$ 539,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "FLEX360TRCLIPONLUCASCL5101",
    "category": "Flex 360 TR Clip On",
    "group": "Flex 360°",
    "line": "Lucas",
    "code": "CL5101",
    "price": 529.9,
    "priceLabel": "R$ 529,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/cl5101.jpg"
  },
  {
    "id": "ACETATOCLIPONMAGNOG5751",
    "category": "Acetato Clip On",
    "group": "Clip-on",
    "line": "Magno",
    "code": "G5751",
    "price": 419.9,
    "priceLabel": "R$ 419,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "ACETATOCLIPONMAGNOG5752",
    "category": "Acetato Clip On",
    "group": "Clip-on",
    "line": "Magno",
    "code": "G5752",
    "price": 449.9,
    "priceLabel": "R$ 449,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "ACETATOCLIPONMAGNOG5753",
    "category": "Acetato Clip On",
    "group": "Clip-on",
    "line": "Magno",
    "code": "G5753",
    "price": 419.9,
    "priceLabel": "R$ 419,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "ACETATOCLIPONMAGNOG5754",
    "category": "Acetato Clip On",
    "group": "Clip-on",
    "line": "Magno",
    "code": "G5754",
    "price": 489.9,
    "priceLabel": "R$ 489,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "ACETATOCLIPONMAGNOG5756",
    "category": "Acetato Clip On",
    "group": "Clip-on",
    "line": "Magno",
    "code": "G5756",
    "price": 449.9,
    "priceLabel": "R$ 449,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "ACETATOCLIPONMAGNOG5768",
    "category": "Acetato Clip On",
    "group": "Clip-on",
    "line": "Magno",
    "code": "G5768",
    "price": 519.9,
    "priceLabel": "R$ 519,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "FLEX360TRCLIPONYURINCL5102",
    "category": "Flex 360 TR Clip On",
    "group": "Flex 360°",
    "line": "Yurin",
    "code": "CL5102",
    "price": 519.9,
    "priceLabel": "R$ 519,90",
    "note": "",
    "size": "54-15-142",
    "colors": 4,
    "image": "assets/modelos/cl5102.jpg"
  },
  {
    "id": "FLEX360TRAUGUSTOCL3102",
    "category": "Flex 360 TR",
    "group": "Flex 360°",
    "line": "Augusto",
    "code": "CL3102",
    "price": 439.9,
    "priceLabel": "R$ 439,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/cl3102.jpg"
  },
  {
    "id": "FLEX360TRFELIPECL3101",
    "category": "Flex 360 TR",
    "group": "Flex 360°",
    "line": "Felipe",
    "code": "CL3101",
    "price": 419.9,
    "priceLabel": "R$ 419,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/cl3101.jpg"
  },
  {
    "id": "FLEX360METALLORENZOCL4102",
    "category": "Flex 360 Metal",
    "group": "Flex 360°",
    "line": "Lorenzo",
    "code": "CL4102",
    "price": 449.9,
    "priceLabel": "R$ 449,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/cl4102.jpg"
  },
  {
    "id": "FLEX360METALNICOLASCL4103",
    "category": "Flex 360 Metal",
    "group": "Flex 360°",
    "line": "Nicolas",
    "code": "CL4103",
    "price": 389.9,
    "priceLabel": "R$ 389,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/cl4103.jpg"
  },
  {
    "id": "FLEX360TRRICARDOCL3103",
    "category": "Flex 360 TR",
    "group": "Flex 360°",
    "line": "Ricardo",
    "code": "CL3103",
    "price": 449.9,
    "priceLabel": "R$ 449,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/cl3103.jpg"
  },
  {
    "id": "FLEX360TRTHOMAZCL3104",
    "category": "Flex 360 TR",
    "group": "Flex 360°",
    "line": "Thomaz",
    "code": "CL3104",
    "price": 419.9,
    "priceLabel": "R$ 419,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/cl3104.jpg"
  },
  {
    "id": "FLEX360METALVALENTINCL4104",
    "category": "Flex 360 Metal",
    "group": "Flex 360°",
    "line": "Valentin",
    "code": "CL4104",
    "price": 419.9,
    "priceLabel": "R$ 419,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/cl4104.jpg"
  },
  {
    "id": "FLEX360METALVICTORCL4101",
    "category": "Flex 360 Metal",
    "group": "Flex 360°",
    "line": "Victor",
    "code": "CL4101",
    "price": 389.9,
    "priceLabel": "R$ 389,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/cl4101.jpg"
  },
  {
    "id": "METALCLG2201",
    "category": "Metal",
    "group": "Metal",
    "line": "CLG",
    "code": "2201",
    "price": 519.9,
    "priceLabel": "R$ 519,90",
    "note": "",
    "size": "",
    "colors": 5,
    "image": "assets/modelos/2201.jpg"
  },
  {
    "id": "METALCLG2202",
    "category": "Metal",
    "group": "Metal",
    "line": "CLG",
    "code": "2202",
    "price": 529.9,
    "priceLabel": "R$ 529,90",
    "note": "",
    "size": "",
    "colors": 5,
    "image": "assets/modelos/2202.jpg"
  },
  {
    "id": "METALCLG2203",
    "category": "Metal",
    "group": "Metal",
    "line": "CLG",
    "code": "2203",
    "price": 489.9,
    "priceLabel": "R$ 489,90",
    "note": "",
    "size": "",
    "colors": 5,
    "image": "assets/modelos/2203.jpg"
  },
  {
    "id": "METALDELICA1424",
    "category": "Metal",
    "group": "Metal",
    "line": "Delica",
    "code": "1424",
    "price": 349.9,
    "priceLabel": "R$ 349,90",
    "note": "",
    "size": "52-17-145",
    "colors": 5,
    "image": "assets/modelos/1424.jpg"
  },
  {
    "id": "METALDELICA1427",
    "category": "Metal",
    "group": "Metal",
    "line": "Delica",
    "code": "1427",
    "price": 259.9,
    "priceLabel": "R$ 259,90",
    "note": "",
    "size": "53-16-145",
    "colors": 6,
    "image": "assets/modelos/1427.jpg"
  },
  {
    "id": "METALDELICA1431",
    "category": "Metal",
    "group": "Metal",
    "line": "Delica",
    "code": "1431",
    "price": 329.9,
    "priceLabel": "R$ 329,90",
    "note": "",
    "size": "50-19-145",
    "colors": 5,
    "image": "assets/modelos/1431.jpg"
  },
  {
    "id": "METALDELICA1438",
    "category": "Metal",
    "group": "Metal",
    "line": "Delica",
    "code": "1438",
    "price": 259.9,
    "priceLabel": "R$ 259,90",
    "note": "",
    "size": "53-17-145",
    "colors": 6,
    "image": "assets/modelos/1438.jpg"
  },
  {
    "id": "METALDELICA8014",
    "category": "Metal",
    "group": "Metal",
    "line": "Delica",
    "code": "8014",
    "price": 319.9,
    "priceLabel": "R$ 319,90",
    "note": "",
    "size": "52-17-145",
    "colors": 4,
    "image": "assets/modelos/8014.jpg"
  },
  {
    "id": "METALDELICAF368",
    "category": "Metal",
    "group": "Metal",
    "line": "Delica",
    "code": "F368",
    "price": 329.9,
    "priceLabel": "R$ 329,90",
    "note": "",
    "size": "55-17-145",
    "colors": 5,
    "image": "assets/modelos/f368.jpg"
  },
  {
    "id": "METALDELICAYJ0245",
    "category": "Metal",
    "group": "Metal",
    "line": "Delica",
    "code": "Yj0245",
    "price": 359.9,
    "priceLabel": "R$ 359,90",
    "note": "",
    "size": "52-20-145",
    "colors": 4,
    "image": "assets/modelos/yj0245.jpg"
  },
  {
    "id": "METALDELICAYJ0246",
    "category": "Metal",
    "group": "Metal",
    "line": "Delica",
    "code": "YJ0246",
    "price": 319.9,
    "priceLabel": "R$ 319,90",
    "note": "",
    "size": "52-17-145",
    "colors": 4,
    "image": "assets/modelos/yj0246.jpg"
  },
  {
    "id": "METALNEO220603",
    "category": "Metal",
    "group": "Metal",
    "line": "Neo",
    "code": "220603",
    "price": 389.9,
    "priceLabel": "R$ 389,90",
    "note": "",
    "size": "",
    "colors": 5,
    "image": "assets/modelos/220603.jpg"
  },
  {
    "id": "METALNEO220606",
    "category": "Metal",
    "group": "Metal",
    "line": "Neo",
    "code": "220606",
    "price": 319.9,
    "priceLabel": "R$ 319,90",
    "note": "",
    "size": "",
    "colors": 4,
    "image": "assets/modelos/220606.jpg"
  },
  {
    "id": "METALNEO220607",
    "category": "Metal",
    "group": "Metal",
    "line": "Neo",
    "code": "220607",
    "price": 329.9,
    "priceLabel": "R$ 329,90",
    "note": "",
    "size": "",
    "colors": 5,
    "image": "assets/modelos/220607.jpg"
  },
  {
    "id": "METALNEO220609",
    "category": "Metal",
    "group": "Metal",
    "line": "Neo",
    "code": "220609",
    "price": 349.9,
    "priceLabel": "R$ 349,90",
    "note": "",
    "size": "",
    "colors": 5,
    "image": "assets/modelos/220609.jpg"
  },
  {
    "id": "METALNEO220611",
    "category": "Metal",
    "group": "Metal",
    "line": "Neo",
    "code": "220611",
    "price": 289.9,
    "priceLabel": "R$ 289,90",
    "note": "",
    "size": "55-14-140",
    "colors": 5,
    "image": "assets/modelos/220611.jpg"
  },
  {
    "id": "METALNEO220613",
    "category": "Metal",
    "group": "Metal",
    "line": "Neo",
    "code": "220613",
    "price": 329.9,
    "priceLabel": "R$ 329,90",
    "note": "",
    "size": "52-18-140",
    "colors": 5,
    "image": "assets/modelos/220613.jpg"
  },
  {
    "id": "METALNEO220615",
    "category": "Metal",
    "group": "Metal",
    "line": "Neo",
    "code": "220615",
    "price": 419.9,
    "priceLabel": "R$ 419,90",
    "note": "",
    "size": "49-19-140",
    "colors": 5,
    "image": "assets/modelos/220615.jpg"
  },
  {
    "id": "METALNEO220618",
    "category": "Metal",
    "group": "Metal",
    "line": "Neo",
    "code": "220618",
    "price": 319.9,
    "priceLabel": "R$ 319,90",
    "note": "",
    "size": "",
    "colors": 5,
    "image": "assets/modelos/220618.jpg"
  },
  {
    "id": "METALNEO221228",
    "category": "Metal",
    "group": "Metal",
    "line": "Neo",
    "code": "221228",
    "price": 449.9,
    "priceLabel": "R$ 449,90",
    "note": "",
    "size": "49-20-138",
    "colors": 5,
    "image": "assets/modelos/221228.jpg"
  },
  {
    "id": "METALNEO221230",
    "category": "Metal",
    "group": "Metal",
    "line": "Neo",
    "code": "221230",
    "price": 289.9,
    "priceLabel": "R$ 289,90",
    "note": "",
    "size": "",
    "colors": 6,
    "image": "assets/modelos/221230.jpg"
  },
  {
    "id": "METALNEO221232",
    "category": "Metal",
    "group": "Metal",
    "line": "Neo",
    "code": "221232",
    "price": 289.9,
    "priceLabel": "R$ 289,90",
    "note": "",
    "size": "51-16-140",
    "colors": 5,
    "image": "assets/modelos/221232.jpg"
  },
  {
    "id": "METALNEO221237",
    "category": "Metal",
    "group": "Metal",
    "line": "Neo",
    "code": "221237",
    "price": 419.9,
    "priceLabel": "R$ 419,90",
    "note": "",
    "size": "48-21-138",
    "colors": 6,
    "image": "assets/modelos/221237.jpg"
  },
  {
    "id": "METALPEGASUS8730",
    "category": "Metal",
    "group": "Metal",
    "line": "Pegasus",
    "code": "8730",
    "price": 379.9,
    "priceLabel": "R$ 379,90",
    "note": "",
    "size": "43-25-140",
    "colors": 4,
    "image": "assets/modelos/8730.jpg"
  },
  {
    "id": "METALPEGASUS8778",
    "category": "Metal",
    "group": "Metal",
    "line": "Pegasus",
    "code": "8778",
    "price": 389.9,
    "priceLabel": "R$ 389,90",
    "note": "",
    "size": "44-23-140",
    "colors": 6,
    "image": "assets/modelos/8778.jpg"
  },
  {
    "id": "METALPEGASUS8795",
    "category": "Metal",
    "group": "Metal",
    "line": "Pegasus",
    "code": "8795",
    "price": 329.9,
    "priceLabel": "R$ 329,90",
    "note": "",
    "size": "43-24-140",
    "colors": 4,
    "image": "assets/modelos/8795.jpg"
  },
  {
    "id": "METALPEGASUS8854",
    "category": "Metal",
    "group": "Metal",
    "line": "Pegasus",
    "code": "8854",
    "price": 389.9,
    "priceLabel": "R$ 389,90",
    "note": "",
    "size": "50-21-140",
    "colors": 4,
    "image": "assets/modelos/8854.jpg"
  },
  {
    "id": "METALPEGASUSECHO87961",
    "category": "Metal",
    "group": "Metal",
    "line": "Pegasus Echo",
    "code": "8796-1",
    "price": 359.9,
    "priceLabel": "R$ 359,90",
    "note": "",
    "size": "44-22-140",
    "colors": 4,
    "image": "assets/modelos/87961.jpg"
  },
  {
    "id": "METALPEGASUSFLUX87941",
    "category": "Metal",
    "group": "Metal",
    "line": "Pegasus Flux",
    "code": "8794-1",
    "price": 329.9,
    "priceLabel": "R$ 329,90",
    "note": "",
    "size": "43-23-140",
    "colors": 4,
    "image": "assets/modelos/87941.jpg"
  },
  {
    "id": "METALPEGASUSLUME8798",
    "category": "Metal",
    "group": "Metal",
    "line": "Pegasus Lume",
    "code": "8798",
    "price": 289.9,
    "priceLabel": "R$ 289,90",
    "note": "",
    "size": "43-25-140",
    "colors": 4,
    "image": "assets/modelos/8798.jpg"
  },
  {
    "id": "METALPEGASUSLYRA8800",
    "category": "Metal",
    "group": "Metal",
    "line": "Pegasus Lyra",
    "code": "8800",
    "price": 359.9,
    "priceLabel": "R$ 359,90",
    "note": "",
    "size": "44-24-140",
    "colors": 4,
    "image": "assets/modelos/8800.jpg"
  },
  {
    "id": "METALPEGASUSORIN8779",
    "category": "Metal",
    "group": "Metal",
    "line": "Pegasus Orin",
    "code": "8779",
    "price": 449.9,
    "priceLabel": "R$ 449,90",
    "note": "",
    "size": "45-24-140",
    "colors": 4,
    "image": "assets/modelos/8779.jpg"
  },
  {
    "id": "METALPEGASUSRENO8801",
    "category": "Metal",
    "group": "Metal",
    "line": "Pegasus Reno",
    "code": "8801",
    "price": 419.9,
    "priceLabel": "R$ 419,90",
    "note": "",
    "size": "43-25-140",
    "colors": 4,
    "image": "assets/modelos/8801.jpg"
  },
  {
    "id": "METALPEGASUSSORA8790",
    "category": "Metal",
    "group": "Metal",
    "line": "Pegasus Sora",
    "code": "8790",
    "price": 379.9,
    "priceLabel": "R$ 379,90",
    "note": "",
    "size": "44-24-140",
    "colors": 6,
    "image": "assets/modelos/8790.jpg"
  },
  {
    "id": "METALPEGASUSTHEO87801",
    "category": "Metal",
    "group": "Metal",
    "line": "Pegasus Theo",
    "code": "8780-1",
    "price": 449.9,
    "priceLabel": "R$ 449,90",
    "note": "",
    "size": "43-22-140",
    "colors": 4,
    "image": "assets/modelos/87801.jpg"
  },
  {
    "id": "METALPEGASUSZETA87771",
    "category": "Metal",
    "group": "Metal",
    "line": "Pegasus Zeta",
    "code": "8777-1",
    "price": 429.9,
    "priceLabel": "R$ 429,90",
    "note": "",
    "size": "45-22-140",
    "colors": 4,
    "image": "assets/modelos/87771.jpg"
  },
  {
    "id": "METALPEGASUSZION87911",
    "category": "Metal",
    "group": "Metal",
    "line": "Pegasus Zion",
    "code": "8791-1",
    "price": 379.9,
    "priceLabel": "R$ 379,90",
    "note": "",
    "size": "43-23-140",
    "colors": 4,
    "image": "assets/modelos/87911.jpg"
  },
  {
    "id": "SOLARACETATO9801",
    "category": "Solar",
    "group": "Solar",
    "line": "Acetato",
    "code": "9801",
    "price": 619.9,
    "priceLabel": "R$ 619,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "SOLARACETATO9804",
    "category": "Solar",
    "group": "Solar",
    "line": "Acetato",
    "code": "9804",
    "price": 649.9,
    "priceLabel": "R$ 649,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "SOLARACETATO9805",
    "category": "Solar",
    "group": "Solar",
    "line": "Acetato",
    "code": "9805",
    "price": 629.9,
    "priceLabel": "R$ 629,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "SOLARACETATO9806",
    "category": "Solar",
    "group": "Solar",
    "line": "Acetato",
    "code": "9806",
    "price": 649.9,
    "priceLabel": "R$ 649,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "SOLARACETATO9808",
    "category": "Solar",
    "group": "Solar",
    "line": "Acetato",
    "code": "9808",
    "price": 549.9,
    "priceLabel": "R$ 549,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "SOLARACETATO9817",
    "category": "Solar",
    "group": "Solar",
    "line": "Acetato",
    "code": "9817",
    "price": 589.9,
    "priceLabel": "R$ 589,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "TRCOMFORTTR6601",
    "category": "TR Comfort",
    "group": "TR Comfort",
    "line": "TR",
    "code": "6601",
    "price": 319.9,
    "priceLabel": "R$ 319,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "TRCOMFORTTR6602",
    "category": "TR Comfort",
    "group": "TR Comfort",
    "line": "TR",
    "code": "6602",
    "price": 319.9,
    "priceLabel": "R$ 319,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "TRCOMFORTTR6603",
    "category": "TR Comfort",
    "group": "TR Comfort",
    "line": "TR",
    "code": "6603",
    "price": 349.9,
    "priceLabel": "R$ 349,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "TRCOMFORTTR6604",
    "category": "TR Comfort",
    "group": "TR Comfort",
    "line": "TR",
    "code": "6604",
    "price": 379.9,
    "priceLabel": "R$ 379,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "TRCOMFORTTR6605",
    "category": "TR Comfort",
    "group": "TR Comfort",
    "line": "TR",
    "code": "6605",
    "price": 419.9,
    "priceLabel": "R$ 419,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "TRCOMFORTTR6606",
    "category": "TR Comfort",
    "group": "TR Comfort",
    "line": "TR",
    "code": "6606",
    "price": 389.9,
    "priceLabel": "R$ 389,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "TRCOMFORTTR6607",
    "category": "TR Comfort",
    "group": "TR Comfort",
    "line": "TR",
    "code": "6607",
    "price": 419.9,
    "priceLabel": "R$ 419,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "TRCOMFORTTR6608",
    "category": "TR Comfort",
    "group": "TR Comfort",
    "line": "TR",
    "code": "6608",
    "price": 429.9,
    "priceLabel": "R$ 429,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "TRCOMFORTTR6609",
    "category": "TR Comfort",
    "group": "TR Comfort",
    "line": "TR",
    "code": "6609",
    "price": 379.9,
    "priceLabel": "R$ 379,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "TRCOMFORTTR6610",
    "category": "TR Comfort",
    "group": "TR Comfort",
    "line": "TR",
    "code": "6610",
    "price": 419.9,
    "priceLabel": "R$ 419,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "TRCOMFORTTR6611",
    "category": "TR Comfort",
    "group": "TR Comfort",
    "line": "TR",
    "code": "6611",
    "price": 349.9,
    "priceLabel": "R$ 349,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  },
  {
    "id": "TRCOMFORTTR6612",
    "category": "TR Comfort",
    "group": "TR Comfort",
    "line": "TR",
    "code": "6612",
    "price": 349.9,
    "priceLabel": "R$ 349,90",
    "note": "",
    "size": "",
    "colors": 0,
    "image": null
  }
];
